### ISSUE TITLE
Cant register ps5, ID do not match

### ISSUE THREAD

**Issue by juakol** [streetpea/chiaki4deck#195]
When adding my ps5 in chiaki4deck I get CE-110032-7 (online PSN id informaton do not match). On the other hand, with Chiaki and the previous version of chiaki4deck I don't have that problem, registration is done correctly with the same ID.

**Comment by streetpea** [comment]
Fixed with 1.6.1

**Comment by Benyo85** [comment]
Unfortunately I still have the error CE-110032-7. Despite version 1.6.1 the registration does not work.
