### ISSUE TITLE
Washed out colors (using HDR)

### ISSUE THREAD

**Issue by LordNoxington** [streetpea/chiaki4deck#214]
**Device/OS**: Steam deck OLED (Stable 3.5.7)
**Configuration**: 1080p, 80mbps, H265 HDR, VAAPI, Placebo (Vulkan), High Quality

When comparing Chiaki4deck HDR against moonlight HDR or a native HDR game, I am noticing the colors are washed out, and seem to be almost limited to the SDR range. I also notice it’s not frequently exceeding 400nits and if it does it will only be a small spike of color on the graphs. HDR is enabled and the HDR badge is displayed during my testing. I am have also compared my PS5 being streamed to SD against my Samsung S95B. All testing has been done through gamescope (game mode) using the instructions outlined in the docs (chiaki-launchers.sh setup).

I saw some other reports of washed out colors from the original HDR enhancement issue and PR tickets, but haven’t been able to find a documented solution. I am using the vaapi decoder, with Placebo renderer and High Quality preset. I have tested other decoders but it didn’t change the outcome.

I have tried various versions of Chiaki4deck from v1.5 to v1.6.1 (clean installs) and SteamOS beta/preview channels but they all share the same behavior.

Chiaki4deck:
![IMG_7735](https://github.com/streetpea/chiaki4deck/assets/89681379/516e9223-177e-47da-9735-0a9ee4bf4f46)

S95B:
![IMG_7738](https://github.com/streetpea/chiaki4deck/assets/89681379/68741d42-2ebb-4ae8-98ed-30a7d6fb5bb6)

Moonlight HDR:
![IMG_7734](https://github.com/streetpea/chiaki4deck/assets/89681379/69421ea3-be37-443a-bfe7-89d5d6f42f59)

Native HDR:
![IMG_7741](https://github.com/streetpea/chiaki4deck/assets/89681379/60573cbc-c658-4d1e-8483-e23bde4be679)

Obviously the images above are not super accurate, but I hope they give a representation of what I am seeing on Chiaki4deck as opposed to other HDR sources.

Please let me know if there is anything else I can try or information I can provide.

**Comment by jbaiter** [comment]
Are you change the in-game HDR settings while streaming? It might be necessary to have your TV on to get HDR actually working with remote play. Just having the badge does not mean the PS5 is actually sending HDR data. See the docs for more details. I'm definitely seeing a lot of pixels with >400nits when I'm e.g. playing cyberpunk.

**Comment by LordNoxington** [comment]
> Are you able to change the in-game HDR settings while streaming? It might be necessary to have your TV on to get HDR actually working with remote play. Just having the badge does not mean the PS5 is actually sending HDR data. See the docs for more details. I'm definitely seeing a lot of pixels with >400nits when I'm e.g. playing cyberpunk.

Hey, appreciate the response! Yes I can manipulate HDR settings in game such as cyberpunk via remote play. Having my TV on/off doesn’t seem to make a difference.

**Comment by LordNoxington** [comment]
I am able to make it produce a full HDR stream,  but it isn’t usable:

![IMG_7756](https://github.com/streetpea/chiaki4deck/assets/89681379/dca7b2ac-c98f-473b-ac68-a93ba7e8fa56)

**Comment by streetpea** [comment]
You may want to check your hdr calibration on your ps5. It may not be properly calibrated to the Steam Deck’s screen

**Comment by LordNoxington** [comment]
> You may want to check your hdr calibration on your ps5. It may not be properly calibrated to the Steam Deck’s screen

I assume you’re referring to 15-15-0 set up? I did go through that process the other evening while trying to solve it. I’ll do some more mucking around today - knowing that it’s working for you guys must mean I’m just doing something wrong haha

**Comment by LordNoxington** [comment]
I am not sure how this is possible, but it seems HDR works in desktop mode but not in game mode…

**Comment by streetpea** [comment]
HDR doesn’t work in desktop mode, desktop mode is SDR.

**Comment by LordNoxington** [comment]
> HDR doesn’t work in desktop mode, desktop mode is SDR.

That’s what I thought… but I cannot get the same color reproduction in game mode as compared to desktop mode

Desktop mode:
![IMG_7759](https://github.com/streetpea/chiaki4deck/assets/89681379/4328ebb7-7f25-46b2-a0a3-d2162cc99b34)

Game Mode:
![IMG_7760](https://github.com/streetpea/chiaki4deck/assets/89681379/ef439d50-c7c3-45b7-afb2-e128ec16f54a)

**Comment by streetpea** [comment]
Try turning off hdr codec and using game mode and see if you prefer the colors then (I.e., sdr vs hdr)

**Comment by streetpea** [comment]
You can check your logs in game mode vs desktop mode and see that hdr is activating in game mode and not desktop mode if you want.

**Comment by LordNoxington** [comment]
> You can check your logs in game mode vs desktop mode and see that hdr is activating in game mode and not desktop mode if you want.

SDR colors do look better than HDR in game mode which is the opposite of what I would expect.

HDR Gamemode log:
[chiaki_session_2024-01-21_11-46-41-985985.log](https://github.com/streetpea/chiaki4deck/files/13999625/chiaki_session_2024-01-21_11-46-41-985985.log)

**Comment by LordNoxington** [comment]
Desktop mode log:
[chiaki_session_2024-01-21_11-55-00-101101.log](https://github.com/streetpea/chiaki4deck/files/13999627/chiaki_session_2024-01-21_11-55-00-101101.log)

**Comment by LordNoxington** [comment]
It could be I am experiencing what @arshiatn was seeing - https://github.com/ValveSoftware/SteamOS/issues/1314

**Comment by ghitamihnea** [comment]
I have the same issue, HDR looks way more washed out, as I described in an older Reddit post one month ago.
PS5 is a calibrated correct 15-15-0 and HDR is active, when checking maxCL I can see values around 1000 and the HDR badge is present.
I have this issue since since the first HDR implementation in chiaki4deck 1.5 and checked if the issue was fixed after every update and it is still present on 1.6.2.
I tried changing every settings in PS5, chiaki and TV and every combination between them and all led to the same result when HDR is active, washout out colours.



HDR:
![IMG_7742](https://github.com/streetpea/chiaki4deck/assets/48406640/e27a0f85-f605-45db-a6ec-8787263815c9)

SDR:
![IMG_7743](https://github.com/streetpea/chiaki4deck/assets/48406640/84e2c5ef-aa6f-4cc7-8fb7-71fec542f77b)

**Comment by LordNoxington** [comment]
I believe SteamOS has a fix coming for it - https://github.com/ValveSoftware/gamescope/commit/52c8cd7e852ff207dd6b6acf875dc53a4677e9c7

**Comment by ghitamihnea** [comment]
I do not think that steamOS preview fixed anything, I am on 3.5.14 steamOS and chiaki 1.6.3 and the issue is still there, reds are orange and everything is pale compared to SDR

Does anyone have any update? Or is just me with the issue, because I do not see any other reports from others.

**Comment by LordNoxington** [comment]
> I do not think that steamOS preview fixed anything, I am on 3.5.14 steamOS and chiaki 1.6.3 and the issue is still there, reds are orange and everything is pale compared to SDR
> 
> Does anyone have any update? Or is just me with the issue, because I do not see any other reports from others.

Yea the change log didn’t mention anything about fixing HDR colours. I think we just wait and hope!

**Comment by arshiatn** [comment]
> > I do not think that steamOS preview fixed anything, I am on 3.5.14 steamOS and chiaki 1.6.3 and the issue is still there, reds are orange and everything is pale compared to SDR
> > Does anyone have any update? Or is just me with the issue, because I do not see any other reports from others.
> 
> Yea the change log didn’t mention anything about fixing HDR colours. I think we just wait and hope!

https://steamcommunity.com/games/1675200/announcements/detail/4064004735511926128?snr=2

I think this one is the fix (3.5.15 Preview). It says: "Improved gamut mapping for HDR titles on Deck OLED".

Can anyone here check it out?

**Comment by ghitamihnea** [comment]
> > > I do not think that steamOS preview fixed anything, I am on 3.5.14 steamOS and chiaki 1.6.3 and the issue is still there, reds are orange and everything is pale compared to SDR
> > > Does anyone have any update? Or is just me with the issue, because I do not see any other reports from others.
> > 
> > 
> > Yea the change log didn’t mention anything about fixing HDR colours. I think we just wait and hope!
> 
> https://steamcommunity.com/games/1675200/announcements/detail/4064004735511926128?snr=2
> 
> I think this one is the fix (3.5.15 Preview). It says: "Improved gamut mapping for HDR titles on Deck OLED".
> 
> Can anyone here check it out?

Yes, just tired it, it seems that the new gamescope version with the fix comes with steamOS 3.5.15.


Colours looks vivid and HDR works great, it is just perfect now.
Thank you everyone for your help and timp!

**Comment by Adrian-dev-sys** [comment]
> > > > I do not think that steamOS preview fixed anything, I am on 3.5.14 steamOS and chiaki 1.6.3 and the issue is still there, reds are orange and everything is pale compared to SDR
> > > > Does anyone have any update? Or is just me with the issue, because I do not see any other reports from others.
> > > 
> > > 
> > > Yea the change log didn’t mention anything about fixing HDR colours. I think we just wait and hope!
> > 
> > 
> > https://steamcommunity.com/games/1675200/announcements/detail/4064004735511926128?snr=2
> > I think this one is the fix (3.5.15 Preview). It says: "Improved gamut mapping for HDR titles on Deck OLED".
> > Can anyone here check it out?
> 
> Yes, just tired it, it seems that the new gamescope version with the fix comes with steamOS 3.5.15.
> 
> Colours looks vivid and HDR works great, it is just perfect now. Thank you everyone for your help and timp!

Hey, I'm also facing the same issue from this thread, updated to steamOS preview 3.5.15, but the colors are still washed out in HDR mode and more vibrant in SDR. I've basically saw no difference after the update. PS5 is running in HDR, calibrated, but when streaming to the deck, the colors aren't right (just like in your Red dead 2 screenshots above). I'm wondering if it's truly fixed in the latest SteamOS or I'm missing something here. Could you post some pics on how it looks now for you after the update in HDR mode?

**Comment by ghitamihnea** [comment]
> > > > > I do not think that steamOS preview fixed anything, I am on 3.5.14 steamOS and chiaki 1.6.3 and the issue is still there, reds are orange and everything is pale compared to SDR
> > > > > Does anyone have any update? Or is just me with the issue, because I do not see any other reports from others.
> > > > 
> > > > 
> > > > Yea the change log didn’t mention anything about fixing HDR colours. I think we just wait and hope!
> > > 
> > > 
> > > https://steamcommunity.com/games/1675200/announcements/detail/4064004735511926128?snr=2
> > > I think this one is the fix (3.5.15 Preview). It says: "Improved gamut mapping for HDR titles on Deck OLED".
> > > Can anyone here check it out?
> > 
> > 
> > Yes, just tired it, it seems that the new gamescope version with the fix comes with steamOS 3.5.15.
> > Colours looks vivid and HDR works great, it is just perfect now. Thank you everyone for your help and timp!
> 
> Hey, I'm also facing the same issue from this thread, updated to steamOS preview 3.5.15, but the colors are still washed out in HDR mode and more vibrant in SDR. I've basically saw no difference after the update. PS5 is running in HDR, calibrated, but when streaming to the deck, the colors aren't right (just like in your Red dead 2 screenshots above). I'm wondering if it's truly fixed in the latest SteamOS or I'm missing something here. Could you post some pics on how it looks now for you after the update in HDR mode?

Yes, sure, here are some pics, but mind the glare, room a little too bright for the camera 
HDR on:
![IMG_8642](https://github.com/streetpea/chiaki4deck/assets/48406640/1a3af7cb-05a7-403a-a166-c3a309f1c9de)

HDR off:
![IMG_8641](https://github.com/streetpea/chiaki4deck/assets/48406640/96d26664-8851-440a-a86a-f3a36f1326f2)

There is still a little bit of difference, but it was expected to not be really identical, not even on my TV SDR and HDR  modes are identical in colours, but games are looking way better in HDR because of the bright highlights and details in shadows.

In both cases steam deck brightness slider was set at around 75% max and HDR on PS5 was set to 15-15-0 clicks and after checking using the steam deck’s HDR tool I can confirm a 1000nits maxCLL.

Steam deck OS: 3.5.15
Chiaki4deck: 1.6.3

Quick tip: I found a workaround to use HDR PS5 remote play with the tv off plugged in to a Samsung TV(S95B).
I’am using the cheapest hdmi 2.1 switch I found (around 11 EUR) like the one below, this one doesn’t even has a usb power connection like the more expensive one I found online and it is working perfect so far, somehow it keeps the HDMI connection alive even with the TV off, I did not have anything else plugged in to the other HDMI port of the switch and it still working like a charm.

![IMG_8643](https://github.com/streetpea/chiaki4deck/assets/48406640/99be610e-3c44-4053-b432-877f3335def5)

**Comment by arshiatn** [comment]
> > > > I do not think that steamOS preview fixed anything, I am on 3.5.14 steamOS and chiaki 1.6.3 and the issue is still there, reds are orange and everything is pale compared to SDR
> > > > Does anyone have any update? Or is just me with the issue, because I do not see any other reports from others.
> > > 
> > > 
> > > Yea the change log didn’t mention anything about fixing HDR colours. I think we just wait and hope!
> > 
> > 
> > https://steamcommunity.com/games/1675200/announcements/detail/4064004735511926128?snr=2
> > I think this one is the fix (3.5.15 Preview). It says: "Improved gamut mapping for HDR titles on Deck OLED".
> > Can anyone here check it out?
> 
> Yes, just tired it, it seems that the new gamescope version with the fix comes with steamOS 3.5.15.
> 
> Colours looks vivid and HDR works great, it is just perfect now. Thank you everyone for your help and timp!


Basically it looks correct now, right? I am gonna update to the preview myself to check it out. I hope they bring this update to stable as fast as possible.

**Comment by streetpea** [comment]
closing since the HDR fix has been released to stable branch for Steam Deck

**Comment by Wiggyweir** [comment]
So I’m still having this issue, I’m only getting max 300 nits from the HDR codec

Chiaki version: 1.8.0
Steamos version: 3.5.19

![IMG_2116](https://github.com/user-attachments/assets/c6fc03ef-7e22-4263-bbeb-e797e3564f8e)
![IMG_2115](https://github.com/user-attachments/assets/d6167814-8266-4afc-b324-a42669e1dadd)

**Comment by kLeR1k** [comment]
I'm facing same issue with chiaki-ng 1.9.1 and SteamOS 3.6.20 on SD OLED.
Colors are washed out with H265 HDR codec and more vibrant (but less bright) with H265 (SDR).
HDR is on (brightness of SD is ~75%)
![20241119_171027](https://github.com/user-attachments/assets/7f709e63-00e3-4afb-9893-31bfac790bdd)
Comparing to my Sony AG8
![20241119_165225](https://github.com/user-attachments/assets/7914b092-14d3-4808-bcac-eb58dba319d4)

And HDR is off
![20241119_171059](https://github.com/user-attachments/assets/8fde2098-9a05-4cbd-8ebf-35327fdff8fd)

Also calibrate HDR settings to 15;15;0 but nothing changed.
My Sony AG8 has setting for color gamut and it is setted up to auto. But when trying to change it to manual - BT.709 is very similar to what I see on SD with HDR on. But BT.2020 option looks like what in "auto" mode is chosen.
Tried to change different settings with libplacebo settings, but had not luck (looks like nothing changes).

Also it does not matter TV turned on/off - always same result.
Any thoughts what can go wrong?

**Comment by streetpea** [comment]
@kLeR1k from my understanding hdr is only activated in game for remote play not on the home menu so you are seeing an sdr image playing in the hdr colorspace.

**Comment by kLeR1k** [comment]
> not on the home menu
On @ghitamihnea photos above looks like HDR also working in home screen (shared them because IMO it is easier to reproduce).
But games with "HDR on" are also washed out. For e.g. A Plague Tale: Requiem working in HDR on PS5/TV, but colors on SD OLED/Chiaki are pale with H265 HDR codec
![20241120_111535](https://github.com/user-attachments/assets/0b9f3209-0235-44ea-a755-5e9034fca9e8)
Almost no bright colors above the sun on the right
![20241120_111223](https://github.com/user-attachments/assets/08095840-301e-4f2a-908a-87ed9d1ac85f)

**Comment by kLeR1k** [comment]
Still trying to investigate and issue.
Turned on verbose logging and trying to find some clue.
Here is full log:
[chiaki_session_2024-11-22_16-52-12-012012.log](https://github.com/user-attachments/files/17871321/chiaki_session_2024-11-22_16-52-12-012012.log)

But found some suspicious attribute
`LaunchSpec: {"sessionId":"sessionId4321","streamResolutions":[{"resolution":{"width":1920,"height":1080},"maxFps":60,"score":10}],"network":{"bwKbpsSent":30000,"bwLoss":0.001000,"mtu":1454,"rtt":2,"ports":[53,2053]},"slotId":1,"appSpecification":{"minFps":30,"minBandwidth":0,"extTitleId":"ps3","version":1,"timeLimit":1,"startTimeout":100,"afkTimeout":100,"afkTimeoutDisconnect":100},"konan":{"ps3AccessToken":"accessToken","ps3RefreshToken":"refreshToken"},"requestGameSpecification":{"model":"bravia_tv","platform":"android","audioChannels":"5.1","language":"sp","acceptButton":"X","connectedControllers":["xinput","ds3","ds4"],**"yuvCoefficient":"bt601"**,"videoEncoderProfile":"hw4.1","audioEncoderProfile":"audio1","adaptiveStreamMode": "resize"},"userProfile":{"onlineId":"psnId","npId":"npId","region":"US","languagesUsed":["en","jp"]},"videoCodec":"hevc","dynamicRange":"HDR","handshakeKey":"WoZC8sxejBk9FaMfS/IcqQ=="}`

Googleed a little and found that bt601 is related to [YCbCr 4:2:2](https://en.wikipedia.org/wiki/Chroma_subsampling#4:2:2) which only possible on my TV with 4k/60Hz config. YCbCr 4:2:2 AFAIK is some sort of reduced color format, so maybe this is the reason... Will continue my researches and find out.

**Comment by kLeR1k** [comment]
D'oh! Looks like my bad - tweaked a little placebo render settings (it turned out that I tweaked wrong parameters in the past) - Color/Saturation specifically - setted it to 1.4 (default is 1.0) and colors on SD looks very similar to what I see on TV. Also raised brightness in in-game HDR calibration screen until reaching 1000 nits on SD. 
And completely picture become a lot more similar to the TV and almost enjoyable.
But I guess that changing Color/Saturation is rough tuning and I need to change some other parameters to get similar but more accurate result. And also would like to rise HDR brightness in placebo so I won't need calibrating HDR in each game and recalibrate it back when switching on the TV.
But there are so much options for placebo and even with their descriptions it is hard to predict what changes will look like on the screen.

Is it possible to make some sort of pop-up screen (like side menu by three-dot button, or Chiaki-stream-menu on L1+R1+L3+R3) where you can change those placebo options on-the-go and see changes on the screen at the same time (not to disconnect from console or traveling on menus each time to change them)? 
Looks like it is feature request, but not sure is changing placebo options without stopping streaming basicly possible.

**Comment by Wiggyweir** [comment]
From what I managed to test a while ago (not in depth):

- If the game had a dedicated HDR toggle in the in game settings, the HDR would display properly on my deck, I verified this using the in built HDR overlay on the deck
- An easy game to test/check this on would be Ratchet and Clank Rift Apart, thats what I tested on and saw the above behaviour

- If the game didn't have a dedicated toggle, the stream would essentially tell me it was HDR, but wouldn't show anything above 400 nits
- the game I confirmed this behaviour on was COD4 Remastered, was showing in HDR on my TV but not on the deck, no HDR toggle in game settings, 

This was a while ago so some of that info might be slightly wrong but you get the gist
